version: '3.6'

services:
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
      env_file:
        - ./.env
      ports:
        - 4000:4000
      networks:
        - defaults
      volumes:
        - .:/home/node/app
        - /home/node/app/node_modules
      restart: always

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    networks:
      - defaults
    ports:
      - 5198:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nodejs_prisma_crud_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local